### ISSUE TITLE
Need a way to get DRUPAL_HASH_SALT for local dev

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/drops-8#103]
From @vendion here at DrupalCamp Atlanta, If we install on Pantheon, but pull down locally, the env variable for the password hash salt isn't there, so we can't log in!

Short term answer is to override with your own value, but we should have a good way to show/share environment variables to help with this case. They could copy it into their settings.local.php.

**Comment by greg-1-anderson** [comment]
There isn't any actual need to share your hash salt between your dev and live sites, is there?  Documenting how to do this yourself is perhaps sufficient?

Note that the [quickstart](https://github.com/pantheon-systems/drush-config-workflow/blob/master/bin/quickstart) script, which makes a local dev environment for a Pantheon site, generates a new hash salt.  Perhaps the solution here would be to make a guide about local dev environment creation.

**Comment by joshkoenig** [comment]
The hash-salt is the same between envs on pantheon because of how it is generated: using the site uuid as part of the random seed.

**Comment by greg-1-anderson** [comment]
Sorry, I meant to say "local environment". The purpose of the hash salt is to protect login sessions; it only needs to be shared in cases where you wish to share login sessions. It is not harmful, and even somewhat convenient for this to be shared between environments; for example, if you log in to the live site, and then copy your live environment to your dev environment, then you will remain logged in.  If you have a different hash salt on your local environment, you'll need to log in again every time you copy the database down from live, but this seems to be at worst a minor inconvenience.

**Comment by joshkoenig** [comment]
Does it not affect how passwords are salted (and therefore validated?)

**Comment by greg-1-anderson** [comment]
I believe it is only used in the one-time login links, and in generating session tokens, not in validating passwords on disk.

https://api.drupal.org/api/drupal/includes%21bootstrap.inc/function/drupal_get_hash_salt/7

**Comment by greg-1-anderson** [comment]
But I haven't tested!  I usually use uli to log in.

**Comment by greg-1-anderson** [comment]
I just did a test, and changing my HASH_SALT did not prevent me from logging in using an existing username/password that was created under the old HASH_SALT.

If you do wish to share your HASH_SALT with your development system, you may retrieve it with Drush:
```
drush @pantheon.sitename.dev ev 'return getenv("DRUPAL_HASH_SALT")' 
```
n.b. You must leave off the trailing semicolon.  If you put the semicolon in, Pantheon will complain that the command is not supported as typed. If you leave it off, Drush will supply it.

**Comment by greg-1-anderson** [comment]
I don't think there is anything further needed here.
