### ISSUE TITLE
Provide a way to persist the services.yml file outside SFTP mode

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/drops-8#111]
Users should not commit a sensitive services.yml file, but need it exist after switching to SFTP mode.
The file path is in .gitignore in the D8 core and in our upstream.

CASE: 49466

**Comment by greg-1-anderson** [comment]
We have this in settings.php:
```
$settings['container_yamls'][] = __DIR__ . '/services.yml';
```
By this mechanism, we could put a services.yml file inside of the files/private directory.

Some experimentation required here.

**Comment by greg-1-anderson** [comment]
Fixed!
