### ISSUE TITLE
Use the right temporary file path on Drupal 8 sites

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/drops-8#114]
By default, Drupal 8 sets the temporary file path to `/tmp`. This is never the best choice on Pantheon, and in fact on 8.0.0-stable, this path causes the configuration export function to fail. (This was still working on recent RC builds.)

The correct path to use on Pantheon is /srv/bindings/<binding id>/tmp.  One easy way to set that path would be for us to add the following to settings.pantheon.php:
```
$config['system.file']['path']['temporary'] = '../tmp';
```
This will cause Drupal 8 to use the correct temporary directory for all operations. The directory thus selected will be correctly displayed in `drush status`; however, admin/config/media/file-system will still display the directory set in the configuration system, and this displayed directory will never be used. This may lead to some confusion.

This should probably be wrapped in an appropriate Pantheon environment check, so that the temporary path is not set in non-Pantheon environments.

**Comment by joshkoenig** [comment]
Better would be to use the ENV vars. Something like:

```php
$config['system.file']['path']['temporary'] = '/srv/bindings/'. PANTHEON_BINDING .'/tmp';
```

Similar to what we do for WP.

**Comment by greg-1-anderson** [comment]
Good idea; I'll code it up like that.

**Comment by ttrowell** [comment]
I could have missed it, but when I dumped `$_ENV` there was a site ID, but no binding data.
Would this be a case for `$_SERVER` ?
```$config['system.file']['path']['temporary'] = '/srv/bindings/'. $_SERVER['HOME'] .'/tmp';```

**Comment by greg-1-anderson** [comment]
@ttrowell: PANTHEON_BINDING is a PHP defined variable.  This works for me:
```
if (defined("PANTHEON_BINDING")) {
  $config['system.file']['path']['temporary'] = '/srv/bindings/'. PANTHEON_BINDING .'/tmp';
}
```

**Comment by greg-1-anderson** [comment]
https://github.com/pantheon-systems/drupal/commit/f433faaf327afcfbc7b1cd042f496d67d81693dd

**Comment by joshkoenig** [comment]
@greg-1-anderson anything holding this up? It's creating issues for users.

**Comment by greg-1-anderson** [comment]
Released as version 8.0.0-p1.  \Drupal::VERSION will still be "8.0.0"; the tag in git is 8.0.0-p1.

The Pantheon version is available as a `define` in settings.php.

**Comment by joemiller** [comment]
I would rather see this as $HOME/tmp instead of /srv/bindings/ID/tmp.  Hardcoding to /srv/bindings prevents us from being able to change that in the future, while $HOME/tmp is something more flexible.

**Comment by greg-1-anderson** [comment]
Seems like a reasonable concern to me. We could adjust this with the release of Drupal 8.0.1. This change won't have any negative impact on current operations, and will be more flexible in the future.

**Comment by greg-1-anderson** [comment]
Needed to deploy an 8.0.0-p2, so adjusted the path to the tmp directory to use $HOME at the same time.

**Comment by bartram** [comment]
With [Compute Optimized Environments](Compute Optimized Environments (COE)), shouldn't `file_temp_path` be `"/tmp"`?

**Comment by greg-1-anderson** [comment]
The file_temp_path is currently calculated as $HOME/tmp:

https://github.com/pantheon-systems/drops-8/blob/default/sites/default/settings.pantheon.php#L149

$HOME is / on COE, so this setting is correct for both heirloom and COE.

**Comment by bartram** [comment]
$HOME is /, so $HOME/tmp is //tmp, which is an invalid path. This causes a fatal error when a module tries to write to the temp directory.

**Comment by greg-1-anderson** [comment]
Could you be more specific about the problem you are having? I find that `file_put_contents("//tmp/foobar", "test");` works, and thereafter I can address `/tmp/foobar` and `//tmp/foobar` equivalently. `file_unmanaged_save_data` also seems to be working for me. Could you provide steps to reproduce any failure scenario you are encountering?

**Comment by bartram** [comment]
I'm using [Flysystem S3](https://www.drupal.org/project/flysystem_s3) module with a private S3 bucket. When a file is requested from Drupal that is referenced in the Flysystem S3 file system, it appears that the module reads the file from S3, writes it to a temporary directory (possibly using `fopen('php://temp')` in the [Flysystem package](https://github.com/thephpleague/flysystem)), and then attempts to serve it to the user with [BinaryFileResponse::setFile](https://api.drupal.org/api/drupal/vendor%21symfony%21http-foundation%21BinaryFileResponse.php/function/BinaryFileResponse%3A%3AsetFile/8.6.x).

I haven't been able to track down exactly where the disconnect is between fetching the file from S3, writing it to a temporary directory, and serving it to the user, but what I have found is that changing `$config['system.file']['path']['temporary']` to `"/tmp"` instead of `"//tmp"` resolves the issue for me.

Maybe the solution is to ensure Drupal is using the same temp directory as PHP, e.g. set `$config['system.file']['path']['temporary']` to [`sys_get_temp_dir()`](https://www.php.net/manual/en/function.sys-get-temp-dir.php)?

**Comment by greg-1-anderson** [comment]
`sys_get_temp_dir()` sounds like an interesting idea. I wonder if simply not setting file_temp_path might produce the same result. We could also wrap our path in `realpath`

**Comment by greg-1-anderson** [comment]
Created a BUG card in JIRA to track internally (BUGS-3300).

**Comment by quicksketch** [comment]
> I have found is that changing `$config['system.file']['path']['temporary']` to `"/tmp"` instead of `"//tmp"` resolves the issue for me.

I also am seeing this on Drupal 9. It seems to prevent the uploading of any file that uses the temporary directory. Note most uploading goes directly to the final destination. In my case, I was unable to upload translation .po files until the double-slash problem was fixed. In my case I used the following:

```
$settings['file_temp_path'] = ini_get('sys_temp_dir');
```

**Comment by greg-1-anderson** [comment]
This fix was inadvertently omitted from pantheon-systems/drupal-integrations. I have committed it there now.

**Comment by quicksketch** [comment]
Thanks! For anyone else, here's the relevant commit: https://github.com/pantheon-systems/drupal-integrations/commit/ef88532ebffb23d7b9081a84e2818cb872d5316e
