### ISSUE TITLE
Do not include settings.pantheon.php file if not PANTHEON_ENVIRONMENT

### ISSUE THREAD

**Issue by ozin7** [pantheon-systems/drops-8#115]
I've got an error during installation Drupal on my localmachine.
exception 'Drupal\Core\Database\ConnectionNotDefinedException' with  [error]
message 'The specified database connection is not defined: default'
in
/var/www/default.localhost/core/lib/Drupal/Core/Database/Database.php:366
Stack trace:
#0
/var/www/default.localhost/core/lib/Drupal/Core/Database/Database.php(171):
Drupal\Core\Database\Database::openConnection('default', 'default')
#1
....

 I think pantheon.settings.php should be included only on PANTHEON_ENVIRONMENT. I've added next code to fix it 
if (isset($_ENV['PANTHEON_ENVIRONMENT'])){
  include __DIR__ . "/settings.pantheon.php";
}

Does it makes sense?

**Comment by greg-1-anderson** [comment]
You should include settings.pantheon.inc in both the Pantheon, and in non-Pantheon environments, [just as the comment says](https://github.com/pantheon-systems/drops-8/blob/master/sites/default/settings.php#L13).

When your site is running in the Pantheon environment, the database settings will be provided in environment and $_SERVER variables.  If you wish to run your site locally, you must provide the database settings by some other method. The recommended way is to create a settings.local.php, and define the $databases structure there.

For an example, see the [quickstart](https://github.com/pantheon-systems/drush-config-workflow/blob/master/bin/quickstart) script, which copies a Pantheon site to your local system. The techniques it uses may or may not be applicable to your particular situation.
