### ISSUE TITLE
Get rid of stale branches for new D8 sites.

### ISSUE THREAD

**Issue by Jaesin** [pantheon-systems/drops-8#120]
If I install a new Drupal 8 site on Pantheon, I have to run the following script to get rid of all the stale branches. 

Why not just prune these when the site is set up?

```bash
#!/bin/bash

git push origin :8.0.0-beta16
git push origin :allow-cache-dirs
git push origin :drush-noise
git push origin :pantheon-binding-tmp
git push origin :8.0.x
git push origin :pantheonprofile
git push origin :private-file-path
git push origin :profile-selection
git push origin :relocate-staging
git push origin :remove-active
git push origin :remove-old
git push origin :schrodingers-cache
git push origin :settings-cleanup
git push origin :spurious-files
git push origin :unify-settings
git push origin :update-8.0-dev-2015-11-17
git push origin :update-8.0.0
git push origin :update-8.0.0-beta16
git push origin :update-8.0.0-rc2
git push origin :update-8.0.0-rc3
git push origin :update-8.0.0-rc4
git push origin :update-8.0.1
git push origin :update-base

# This one has a matching tag.
git push origin --delete refs/heads/8.0.0-rc1
```

**Comment by stevector** [comment]
@greg-1-anderson, any reason for keeping these old branches around? I'd like to see them removed too, or at least not carried over to individual sites.

**Comment by greg-1-anderson** [comment]
The thing about git is that, while you can delete things all you want, but they don't always stay deleted. This isn't so bad with branches; shouldn't be anyone pushing the stale ones around, so hopefully we'll be good here.

I'll remove our update branches after each deploy from here on out.
