### ISSUE TITLE
"Standard" Module is Not Found. Breaks CM Operations.  Still.

### ISSUE THREAD

**Issue by chris-stg** [pantheon-systems/drops-8#126]
I'm experiencing the same issue as detailed in #49.  Using Drupal 8.0.3, everything up-to-date.  settings.pantheon.php is latest version.

**Comment by greg-1-anderson** [comment]
Is this a new site, or an old site that has been updated? Are you importing CM exported from the same Drupal site where you are seeing the error message, or are you importing CM that was exported from a different site?  Here, "same site" means the database generated by site-install -- same code + different run of 'site install' == different site, which can sometimes cause issues with Drupal 8.  If working with local sites, please try installing on Pantheon, and then copying your database down to your local site before working with CM.

This may or may not be the source of your issue; in any event, please provide specific steps to reproduce .

**Comment by chris-stg** [comment]
Same site on Pantheon, but different environments.  I'm trying to import CM that was exported from the development instance to the testing instance.  The database of the testing instance was copied from the live instance just prior to the import attempt.

**Comment by greg-1-anderson** [comment]
Tried to reproduce your problem, but it worked fine for me.

My steps:

1. Create a new Drupal 8 site
2. "Visit development site" and Install it
3. Commit settings.php via the Pantheon dashboard
4. Create the test environment
5. Export changes from dev via Drush
6. Commit the configuration from the dashboard
7. Attempt to import to test via Drush -- error, configuration empty
8. Deploy code from dev to test
9. Attempt to import to test via Drush -- ok, but no action, nothing to change
10. Make a configuration change to site title and slogan
11. Export config via Drush, and commit from the dashboard
12. Deploy code from dev to test
13. Import config via Drush -- worked, site name and slogan changed

Are you importing / exporting via Drush?  Are you moving config via git + the Dashboard?  Or are you using some other mechanism?  Probably should not matter, but wondering if there is a difference here.

I am also wondering if you did step (3).  If you install your Drupal 8 site and then switch from sftp mode to git mode on the Pantheon dashboard without committing the change that Drupal makes to settings.php (Pantheon will warn you before throwing it away), then that could cause potentially cause this problem. Haven't tried to reproduce like that yet to be sure, but you definitely need the installation profile identified in settings.php in Drupal 8.

**Comment by chris-stg** [comment]
I created a Drupal site via the dashboard.  The initial commit made automatically was empty, just the tag "pantheon.initialize" was created.  There were no files to be committed after the install when I switched from SFTP to Git mode.  I created a new site just now, and see the same thing -- nothing to commit after initialization.

As far as the config tasks, I performed them using Terminus and drush.  And, yes, using git to commit configuration files.  Actually, I used this Pantheon doc:  https://pantheon.io/docs/articles/drupal/8/configuration-management/

**Comment by greg-1-anderson** [comment]
I'm confused by your report above. You are not seeing a file to be committed after installing Drupal 8, as shown below?

![screen shot 2016-02-08 at 1 32 27 pm](https://cloud.githubusercontent.com/assets/612191/12899940/9c1f3bea-ce68-11e5-8308-20d4005009cd.png)

And you say that if you switch to 'git' mode after installing, then you do not see a warning, like below?

![screen shot 2016-02-08 at 1 32 46 pm](https://cloud.githubusercontent.com/assets/612191/12899956/ae791996-ce68-11e5-87f9-d93dc8b0db16.png)

Are you installing with the 'standard' installation profile, 'minimal' or other?  I was using standard; will wipe and try again with minimal, and see if behavior has changed there.

**Comment by greg-1-anderson** [comment]
Just tested with 'minimal' profile, and I got the same results as the screenshots I posted above.

**Comment by chris-stg** [comment]
That's correct, I'm not seeing that.  Just created a new site, and here's how it looks after the site initializes:
![image](https://cloud.githubusercontent.com/assets/15250871/12900459/8c2ebef6-ce84-11e5-88cf-499edb91de1a.png)

**Comment by greg-1-anderson** [comment]
So far so good.  Click on "Visit Development Site", install Drupal 8 with the profile of your choice, and then come back to the dashboard and commit the settings.php file. Then [test per steps 4-13 above](https://github.com/pantheon-systems/drops-8/issues/126#issuecomment-181514752) and see if you still encounter a problem.

**Comment by greg-1-anderson** [comment]
Make sure that your settings.php file has an entry for the installation profile:

![screen shot 2016-02-08 at 2 32 03 pm](https://cloud.githubusercontent.com/assets/612191/12901476/d757bb4e-ce70-11e5-9d85-7e3f5f57c6b4.png)

(Check this on your original site that is having problems and confirm that it is there.)

**Comment by chris-stg** [comment]
My settings.php files don't have any install_profile value set:

`<?php

/**
 * Load services definition file.
 */
$settings['container_yamls'][] = __DIR__ . '/services.yml';

/**
 * Include the Pantheon-specific settings file.
 *
 * n.b. The settings.pantheon.php file makes some changes
 *      that affect all envrionments that this site
 *      exists in.  Always include this file, even in
 *      a local development environment, to insure that
 *      the site settings remain consistent.
 */
include __DIR__ . "/settings.pantheon.php";

/**
 * If there is a local settings file, then include it
 */
$local_settings = __DIR__ . "/settings.local.php";
if (file_exists($local_settings)) {
  include $local_settings;
}`

Adding `$settings['install_profile'] = 'standard';` fixes the problem.  So, perhaps the real issue is that the settings.php is not being updated during site initialization.  It's strange that you're not able to repeat the issue, but I've set up 2 new sites as part of troubleshooting this and both have the same problem: settings.php not setup correctly.

**Comment by greg-1-anderson** [comment]
You are installing in 'sftp' mode, I presume? Typically I get permission denied during installation when in git mode, so I doubt this is a difference. I can't think of a good reason why your settings.php file is not being updated during installation, though.

**Comment by bmackinney** [comment]
Also, to clarify, by "installing", @greg-1-anderson is referring to visiting the development site, at http://dev-drupal-8-site-stg.pantheon.io and installing drupal while the dev environment is in SFTP mode. When you select standard or minimal profile, Drupal will add the line to `settings.php`. From there you can add your configs and import them.

**Comment by greg-1-anderson** [comment]
@chris-stg: Are you installing the site by going to 'visit development site', or are you using terminus / drush?

**Comment by chris-stg** [comment]
Sorry about the red herring -- the sites I spun up yesterday had not been installed yet.  After installation, there was the correct settings.php file to commit.  The original site I was having this issue with was installed, and I'm 99% sure I did not delete any files to be committed.  That site was setup in early January.  In any case, this can be closed.  Thanks for all of the assistance!
