### ISSUE TITLE
using BrowserTestBase fails to open settings.pantheon.php

### ISSUE THREAD

**Issue by esclapes** [pantheon-systems/drops-8#130]
I am trying to test a custom module extending `BrowserTestBase` following [this change record](https://www.drupal.org/node/2469723), but it fails during the `installDrupal` method.

It is installing a test site based on `default.settings.php` but it does not copy the `pantheon` and `local` versions and fails on the include. 

I can fix my `default.settings.php`, but not sure what would be the approach upstream.

**Comment by stevector** [comment]
I think this PR may fix what you are describing: https://github.com/pantheon-systems/drops-8/pull/134

**Comment by greg-1-anderson** [comment]
#134 has been merged.
