### ISSUE TITLE
Drupal 8.0 doesn't support OPTIONS requests.

### ISSUE THREAD

**Issue by gabesullice** [pantheon-systems/drops-8#136]
Drupal 8.0.x does not have support for OPTIONS HTTP requests and responds with a 405 Method Not Allowed. This is especially painful when using D8 as an API server, since POST, PATCH, DELETE, and GET requests with custom headers (like when using basic auth) all get preflighted during Xhr browser requests. This effectively makes D8 as an API server a 'no go'.

Drupal 8.1 fixes this issue (see https://www.drupal.org/node/2237231), however, on Pantheon, there seems to be no solution to this issue when running Drupal stable (8.0.5 ATM).

I see two resolutions to this:

1. Backport the fix from 8.1 to drops-8.0.x
2. Provide NGINX level responses to OPTIONS requests on the Pantheon platform. That would  look something like the server config below.

```
location / {
    if ($request_method = OPTIONS ) {
        add_header Access-Control-Allow-Origin $http_host;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS";
        add_header Access-Control-Allow-Headers "Accept, Content-Type, Authorization";
        add_header Access-Control-Allow-Credentials "true";
        add_header Content-Length 0;
        add_header Content-Type text/plain;
        return 200;
    }
}
```

**Comment by gabesullice** [comment]
I should note, my attempts to apply the D.O patch to 8.0.5 did _not_ seem to resolve the issue. More work would be needed to this patch to directly apply it to 8.0.x.

**Comment by greg-1-anderson** [comment]
I don't think that we are going to get into the business of backporting 8.1.x enhancements to 8.0.x.  If drupal.org doesn't backport it, it will have to wait until 8.1.x is released.
