### ISSUE TITLE
Support `PANTHEON_DATABASE_STATE` in Kalabox

### ISSUE THREAD

**Issue by pirog** [pantheon-systems/drops-8#139]
Holla holla! 

Doing another sync on Drupal 8 support over at https://github.com/kalabox/kalabox/issues/1193 and noticed one big change that is a little harder for us to replicate on the Kalabox side. That is the existence and value of `PANTHEON_DATABASE_STATE`. Without this on Kalabox users need to have a DB spun up on Pantheon before they pull their site down. 

Admittedly, i *think* most users will have done this but it would be nice to not get noise on our end for the uesrs who have not. We are using a `prepend.php` file like you guys to set needed `$_ENV` and `$_SERVER` values but i'm not exactly clear on the ideal way to set `PANTHEON_DATABASE_STATE`. 

How are you guys setting `PANTHEON_DATABASE_STATE`? Are you just checking for some rando core table?

**Comment by greg-1-anderson** [comment]
Hey; sorry I missed this issue previously.  We initialize `PANTHEON_DATABASE_STATE` to either `ok` or `empty`, depending on whether any database tables are found. When searching for tables, we ignore any whose name begins with '_' or 'cache'.

**Comment by pirog** [comment]
thanks @greg-1-anderson

we are currently doing a weaker check than this but i think it probably is sufficient for the local use case.
