### ISSUE TITLE
Merge conflict in default.settings.php

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/drops-8#165]
If you manually copy default.settings.php to settings.php as part of installation, installation will fail.

Fortunately, you do not need to manually copy this file as part of installation. Simply visit your Development site while the site is in SFTP mode and follow installation. A settings.php file will be generated automatically, which you then can commit via the Pantheon site dashboard.

The merge conflict is fixed by https://github.com/pantheon-systems/drops-8/pull/164 and will be as part of the next Drupal 8 update.

**Comment by greg-1-anderson** [comment]
This has been merged in.
