### ISSUE TITLE
Create tag for Drupal 8.2.7

### ISSUE THREAD

**Issue by danielnv18** [pantheon-systems/drops-8#171]
The code was merge #170  but release tag is missing. I'm getting 404 using composer. For example this does work https://raw.githubusercontent.com/pantheon-systems/drops-8/8.2.6/.csslintrc  but this one doesn't https://raw.githubusercontent.com/pantheon-systems/drops-8/8.2.7/.csslintrc

![screenshot 2017-03-16 08 47 36](https://cloud.githubusercontent.com/assets/3136353/24002023/3d457e00-0a25-11e7-95d7-85baebdc5857.png)

**Comment by danielnv18** [comment]
I'm using https://github.com/pantheon-systems/example-drops-8-composer

**Comment by greg-1-anderson** [comment]
Accidentally omitted `git push --tags`. Did that now. Thank you for reporting.
