### ISSUE TITLE
"core" key commented out in content_moderation.info.yml in 8.3.0.

### ISSUE THREAD

**Issue by imclean557** [pantheon-systems/drops-8#174]
In Drops 8.3.0, the "core" line is commented out of the file `core/modules/content_moderation/content_moderation.info.yml` resulting in an error and an unusable site, presumably because the Drupal packaging script doesn't add anything to the .info.yml file of experimental modules. 

> Drupal\Core\Extension\InfoParserException: Missing required keys (core) in core/modules/content_moderation/content_moderation.info.yml in Drupal\Core\Extension\InfoParserDynamic->parse() (line 29 of /.../core/lib/Drupal/Core/Extension/InfoParserDynamic.php) #0 

Uncommenting the line resolves the issue.

**Comment by greg-1-anderson** [comment]
[content_moderation.info.yml](https://github.com/pantheon-systems/drops-8/blob/8.3.0/core/modules/content_moderation/content_moderation.info.yml#L5) looks right to me in drops-8 version 8.3.0, and in the upstream on drupal.org.

**Comment by imclean557** [comment]
It does indeed, which is odd. I did check there first.  Updating with the Pantheon console failed. After viewing the site, I downloaded the logs and saw the above error message.

I ended up merging locally using the recommended command:

`git pull -Xtheirs git://github.com/pantheon-systems/drops-8.git master`

This didn't "fail" like Pantheon reported, but the result was the same. I was able to resolve it quickly. The complete file contents:

```
name: 'Content Moderation'
type: module
description: 'Provides moderation states for content'
# version: VERSION
# core: 8.x
package: Core (Experimental)
configure: entity.workflow.collection
dependencies:
  - workflows

```

**Comment by imclean557** [comment]
Some further information, this is the 8.2.7 version of the same file:

```
name: 'Content Moderation'
type: module
description: 'Provides moderation states for content'
# version: VERSION
# core: 8.x
package: Core (Experimental)
configure: content_moderation.overview

# Information added by Drupal.org packaging script on 2017-03-15
version: '8.2.7'
core: '8.x'
project: 'drupal'
datestamp: 1489609681

```

**Comment by greg-1-anderson** [comment]
That's odd, the [8.2.7 version on drops-8](https://github.com/pantheon-systems/drops-8/blob/8.2.7/core/modules/content_moderation/content_moderation.info.yml#L5) does not look like that.

**Comment by greg-1-anderson** [comment]
I don't have even a minute to check an installed site right now though.

**Comment by imclean557** [comment]
After checking with the team, there may have been a manual update of core/modules from drupal.org due to a conflict at some point. I'll close this until/unless I receive information to say otherwise.

**Comment by greg-1-anderson** [comment]
Doing stuff with `drush make` / `drush dl` / `drush pm-updatecode` would explain this.
