### ISSUE TITLE
Minor update from 8.1.0 to 8.2.0 to 8.3.0

### ISSUE THREAD

**Issue by shenzhuxi** [pantheon-systems/drops-8#175]
I have 2 Drupal 8 sites on pantheonsite.io. 

For the first site, after I used the dashboard update from 8.1.0 to 8.2.0, the edited composer.json file was merged back to new Drupal core automatically.  

```
Author: Pantheon <root@getpantheon.com>
Date:   Tue Oct 11 09:09:32 2016 +0000

    Update to Drupal 8.2.0. For more information, see https://www.drupal.org/project/drupal/releases/8.2.0
    
    Was: Merge branch 'master' of git://github.com/pantheon-systems/drops-8
```

For the second site, after I used the dashboard update from 8.2.0 to 8.3.0, composer.json file was replaced with the new one from Drupal 8.3.0 and all the modules information was not merged back. 

```
Author: Pantheon Automation <bot@getpantheon.com>
Date:   Wed Apr 5 17:48:30 2017 -0700

    Update to Drupal 8.3.0. For more information, see https://www.drupal.org/project/drupal/releases/8.3.0
```

**Comment by greg-1-anderson** [comment]
This is the expected result if using Composer and Pantheon dashboard updates together. Any time that Drupal modifies the composer.json file, which could happen on any minor release, then any user-modified changes to this file (e.g. all of your contrib modules) will be removed.

The recommended way to use Composer with Pantheon is to use the [example drops-8 composer](https://github.com/pantheon-systems/example-drops-8-composer) project.
