### ISSUE TITLE
Add Pantheon Backend Cache Clearing and Cron Hooks

### ISSUE THREAD

**Issue by populist** [pantheon-systems/drops-8#19]
The Pantheon API module will need to be updated to Drupal 8.  Additionally, our Pantheon cron will need to be updated to enable said module using the appropriate D8 method (https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Extension!ModuleHandler.php/function/ModuleHandler%3A%3Ainstall/8).

**Comment by populist** [comment]
Here is the business logic code we need to run:

/**
 * The Drupal 8 hook.
 */
function pantheon_api_cache_flush() {
  register_shutdown_function('pantheon_api_flush_caches_shutdown');
}

**Comment by populist** [comment]
We do not need to support a Pantheon API module, but do need to modify Pantheon's backend functionality to run two specific functions as hooks.

**Comment by greg-1-anderson** [comment]
[ModuleHandler::addModule](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21ModuleHandler.php/function/ModuleHandler%3A%3AaddModule/8) is the current Drupal 8 API for enabling modules.

Rather than conditionalizing this behavior in pantheon_cron (or wherever it ends up going), perhaps it would be better to do this with a call to `drush pm-enable`, and allow Drush to handle calling the correct site-specific enable API.

**Comment by greg-1-anderson** [comment]
So, [pantheon_api_cache_flush()](https://github.com/pantheon-cookbooks/endpoint/blob/9b206cf1c9e35e51be4b7fbabaf7071d5e61980f/templates/default/includes/pantheon.php#L362) and [pantheon_api_cron()](https://github.com/pantheon-cookbooks/endpoint/blob/9b206cf1c9e35e51be4b7fbabaf7071d5e61980f/templates/default/includes/pantheon.php#L385) are now found in [pantheon-cookbooks/endpoint/includes/pantheon.php](https://github.com/pantheon-cookbooks/endpoint/blob/master/templates/default/includes/pantheon.php), so I think the note from [17 Aug](https://github.com/pantheon-systems/drops-8/issues/19#issuecomment-131960347) has been handled.

 pantheon.drush.inc still needs some work; see pantheon-cookbooks/drush#6.

**Comment by populist** [comment]
hook_cron() remains the same in D8 - https://api.drupal.org/api/drupal/core!core.api.php/function/hook_cron/8

hook_cache_flush() is now hook_flush_cache() - https://api.drupal.org/api/drupal/core!core.api.php/function/hook_cache_flush/8

**Comment by greg-1-anderson** [comment]
Fixed by https://github.com/pantheon-cookbooks/drush/pull/9
