### ISSUE TITLE
Ability to Inject Drupal 8 Config Values into Settings.php

### ISSUE THREAD

**Issue by populist** [pantheon-systems/drops-8#2]
Unlike the installation process for Drupal 7, Drupal 8 requires (on behalf of CMI) that the values for the configuration directories be available to settings.php. This is typically written during installation and look like this:

$config_directories['active']['path'] = 'config_1-lRVHZQPcBvES1GZkcB4OMzcH9qHNiqTxhEj706e3U/active';
$config_directories['staging']['path'] = 'config_1-lRVHZQPcBvES1GZkcB4OMzcH9qHNiqTxhEj706e3U/staging';

Since we want to skip this step all together, we will need to figure out how to modify this write/read behavior so that Pantheon can define the $config_directories values in the same way we currently do for the $databases.

**Comment by populist** [comment]
As a quick note, it probably is best to have the configuration settings happen in settings.php WITHOUT a wrapper for running on Pantheon so folks who move elsewhere or have a local development setup still are able to find where their configuration lives.

**Comment by populist** [comment]
We should also add a message that describes the privacy settings of these values and consider moving it to /private so it is private + versionable on Pantheon.

**Comment by greg-1-anderson** [comment]
I would propose the following note about privacy and config paths:
```
IMPORTANT SECURITY NOTE:  The configuration paths set up
below are secure when running your site on Pantheon.  If you
migrate your site to another environment on the public internet, 
you should relocate these locations. See "After Installation"
at https://www.drupal.org/node/2431247
```

**Comment by greg-1-anderson** [comment]
Everything mentioned here has been committed.
