### ISSUE TITLE
I can't get Drush 7 to execure config export.

### ISSUE THREAD

**Issue by Jaesin** [pantheon-systems/drops-8#20]
Seems more like a support thing but this is what I get when I try to use Drush 7 with our D8 install.

```
xxxxxxxxxxxxxxxxxx#: d7 @C8.dev cex
Drush 5.10.0 does not support Drupal . Use Drush 4 instead.              [error]

Fatal error: Class 'Drupal' not found in /srv/bindings/7f516237c15e4b4ea38f27e9daff4bf5/code/core/includes/bootstrap.inc on line 178
Ok
Drush command terminated abnormally due to an unrecoverable error.       [error]
Error: Class 'Drupal' not found in
/srv/bindings/7f516237c15e4b4ea38f27e9daff4bf5/code/core/includes/bootstrap.inc,
line 178
```

**Comment by fosterinteractive** [comment]
I'm pretty sure pantheon doesn't support Drush 7 - Can anyone confirm?

**Comment by davidstrauss** [comment]
We can toggle between Drush 5 and 7 on a per-site basis via a support ticket. We default Drupal 6/7 to Drush 5 and Drupal 8 to Drush 7.

**Comment by populist** [comment]
As an update, Pantheon does support Drush 7 but likely didn't in 2014 when you filed this issue. Should be good to go now, running the latest RC1 of Drush 7.
