### ISSUE TITLE
Upgrade to 8.0.0-beta6 cause fatal error.

### ISSUE THREAD

**Issue by mikevanwinkle** [pantheon-systems/drops-8#23]

**Comment by elvis2** [comment]
I don't think this fix worked. I created a pantheon ticket if you have access and want to read more details:

https://dashboard.pantheon.io/sites/81449655-d583-4307-8558-c3744addf38f#support/ticket/33428

**Comment by mikevanwinkle** [comment]
I can confirm that something's not quite right here. I'm looking at it.

**Comment by elvis2** [comment]
Hi Mike,

Have you had a chance to look into this?

Elvis

**Comment by mikevanwinkle** [comment]
Hi Elvis, we have a beta 7 out now, have you updated your upstream?

On Sat, Mar 7, 2015 at 10:00 AM, Elvis McNeely <notifications@github.com>
wrote:

> Hi Mike,
>
> Have you had a chance to look into this?
>
> Elvis
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pantheon-systems/drops-8/issues/23#issuecomment-77701126>
> .
>



-- 
Mike Van Winkle
708-289-3136
mike@mikevanwinkle.com
http://www.mikevanwinkle.com
http://www.twitter.com/mpvanwinkle
http://www.facebook.com/mpvanwinkle


"All excellent things are as difficult as they are rare." -Spinoza

**Comment by populist** [comment]
Going to go ahead and close since since the updated beta installs correctly.

**Comment by populist** [comment]
As of Beta 14 this does not look like it is required anymore.
