### ISSUE TITLE
8.6.1 drop missing scaffold files

### ISSUE THREAD

**Issue by jselt** [pantheon-systems/drops-8#230]
Using Circle CI to build and getting these errors:

``` Failed to download https://raw.githubusercontent.com/pantheon-systems/drops-8/8.6.1/sites/default/default.services.pantheon.preproduction.yml, https://raw.githubusercontent.com/pantheon-systems/drops-8/8.6.1/sites/example.settings.local.php, https://raw.githubusercontent.com/pantheon-systems/drops-8/8.6.1/sites/default/default.services.yml, https://raw.githubusercontent.com/pantheon-systems/drops-8/8.6.1/robots.txt, https://raw.githubusercontent.com/pantheon-systems/drops-8/8.6.1/sites/example.sites.php, https://raw.githubusercontent.com/pantheon-systems/drops-8/8.6.1/sites/default/settings.pantheon.php, https://raw.githubusercontent.com/pantheon-systems/drops-8/8.6.1/update.php, https://raw.githubusercontent.com/pantheon-systems/drops-8/8.6.1/index.php, https://raw.githubusercontent.com/pantheon-systems/drops-8/8.6.1/sites/development.services.yml, https://raw.githubusercontent.com/pantheon-systems/drops-8/8.6.1/sites/default/default.settings.php, https://raw.githubusercontent.com/pantheon-systems/drops-8/8.6.1/.gitattributes, https://raw.githubusercontent.com/pantheon-systems/drops-8/8.6.1/.ht.router.php ```

All generate 404s from Github

**Comment by jselt** [comment]
I see the issue - the composer.json file is looking for an 8.6.1 tag since it's pulling the version from the core version from drupal and there isn't an 8.6.1 tag here yet.

Just set composer to 8.6 for now.

**Comment by albertski** [comment]
Can we leave the issue open so the 8.6.1 tag gets created?

**Comment by greg-1-anderson** [comment]
I only just became aware of the 8.6.1 release. I'll get a release for that spun up right away.

**Comment by greg-1-anderson** [comment]
It looks like 8.6.1 is only necessary for folks who were experiencing problems upgrading from Drupal 8.5.x.

**Comment by greg-1-anderson** [comment]
Test are running here:

https://github.com/pantheon-systems/drops-8/pull/231

**Comment by greg-1-anderson** [comment]
Did not remember to update this issue, but the 8.6.1 tags were created this morning & should all exist now.
