### ISSUE TITLE
Drupal 8.6.0 commit downgrades PHP in upstream

### ISSUE THREAD

**Issue by dficker** [pantheon-systems/drops-8#232]
For some reason (I'm guessing inadvertently) this was un-done in the Drupal 8.6.0 update commit?  Is there a reason for that?

I don't want to go back so I guess I will set a `php_version` in my `pantheon.yml` file.

Thanks!

_Originally posted by @dficker in https://github.com/pantheon-systems/drops-8/pull/221#issuecomment-422923653_

**Comment by greg-1-anderson** [comment]
Yes, that was done in error. Thanks for reporting this.
