### ISSUE TITLE
Support for WebP within PHP GD library

### ISSUE THREAD

**Issue by scotteuser** [pantheon-systems/drops-8#255]
Can we please have WebP support in PHP so [image_webp()](http://php.net/manual/en/function.imagewebp.php) can be used? The [benefits of using webp](https://developers.google.com/speed/webp/faq) are great and [browser support is broad](https://caniuse.com/#feat=webp) with fully functioning fallbacks.

Pantheon output of gd_info():
```
Array
(
  [GD Version] => bundled (2.1.0 compatible)
  [FreeType Support] => 1
  [FreeType Linkage] => with freetype
  [GIF Read Support] => 1
  [GIF Create Support] => 1
  [JPEG Support] => 1
  [PNG Support] => 1
  [WBMP Support] => 1
  [XPM Support] => 1
  [XBM Support] => 1
  [WebP Support] => 
  [BMP Support] => 1
  [JIS-mapped Japanese Font Support] => 
)

```
Whereas in ddev for instance:

```
Array
(
  [GD Version] => 2.2.5
  [FreeType Support] => 1
  [FreeType Linkage] => with freetype
  [GIF Read Support] => 1
  [GIF Create Support] => 1
  [JPEG Support] => 1
  [PNG Support] => 1
  [WBMP Support] => 1
  [XPM Support] => 1
  [XBM Support] => 1
  [WebP Support] => 1
  [BMP Support] => 1
  [JIS-mapped Japanese Font Support] => 
)
```

**Comment by greg-1-anderson** [comment]
Supporting this is a simple matter of ensuring that ImageMagick is built with libwebp-dev. Here's an explanation for Ubuntu:

https://askubuntu.com/questions/251950/imagemagick-convert-cant-convert-to-webp

**Comment by greg-1-anderson** [comment]
This is a platform issue, though, not a drops-8 issue. I added this request to [FEAT-335](https://getpantheon.atlassian.net/browse/FEAT-335) (internal link)

**Comment by scotteuser** [comment]
Thanks! Sorry I did ask the live chat on Pantheon where to point and they said here. Thanks for correcting.

**Comment by greg-1-anderson** [comment]
No worries, it got to the right place.

**Comment by jenlampton** [comment]
I thought ImageMagick was an alternative to GD? Does GD require ImageMagick in order to support WebP?

**Comment by greg-1-anderson** [comment]
Sorry, I switched graphics packages in my comment above. Pantheon supports webp for both Imagemagik and GD in PHP 7.4. You can check the capabilities of Pantheon's PHP here:

https://v74-php-info.pantheonsite.io/

**Comment by jenlampton** [comment]
Ah, that makes more sense. Thanks for the link!

**Comment by scotteuser** [comment]
Great thank you, definitely going to make good use of the new feature!

**Comment by ElusiveMind** [comment]
Is webP supported on Pantheon Multidev?

**Comment by namespacebrian** [comment]
@ElusiveMind 
> Is webP supported on Pantheon Multidev?

Multidev environments use exactly the same PHP runtime as dev/test/live.  GD WebP should work in all environments running PHP 7+.  You can verify this by creating a stand-alone .php file with `phpinfo();` in it and searching the output for "webP".

On pages like https://v74-php-info.pantheonsite.io/, `v74` _is a multidev environment_.  The site name is `php-info` and `v74` is the multidev environment.
