### ISSUE TITLE
The temporary file path in 8.8.0 is now a setting in settings.php

### ISSUE THREAD

**Issue by supats1** [pantheon-systems/drops-8#287]
In the release notes (https://www.drupal.org/project/drupal/releases/8.8.0) under "Other important update information":

- The temporary file path is now a setting in settings.php, and is no longer stored in configuration. If your site is not using /tmp, you must update settings.php before running database updates:

 $settings['file_temp_path'] = '/path/to/your/temporary/folder';

It appears that Pantheon's settings.pantheon.php needs to be updated accordingly. Is this correct?

Thanks,
Joe

**Comment by guylyons** [comment]
Is this also relative to the Drupal 7 upsteam? I'm having potential issues related to the /tmp directory.

**Comment by greg-1-anderson** [comment]
Fixed by #286

**Comment by supats1** [comment]
Thanks, @greg-1-anderson !
