### ISSUE TITLE
8.8.4 drop missing scaffold files

### ISSUE THREAD

**Issue by johnbocaligsage** [pantheon-systems/drops-8#298]
- .gitattributes (https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.4/.gitattributes): Downloading (failed)
  - .ht.router.php (https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.4/.ht.router.php): Downloading (failed)
  - index.php (https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.4/index.php): Downloading (failed)
  - robots.txt (https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.4/robots.txt): Downloading (failed)
  - sites/default/default.services.yml (https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.4/sites/default/default.services.yml): Downloading (failed)
  - sites/default/default.settings.php (https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.4/sites/default/default.settings.php): Downloading (failed)
  - sites/development.services.yml (https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.4/sites/development.services.yml): Downloading (failed)
  - sites/example.settings.local.php (https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.4/sites/example.settings.local.php): Downloading (failed)
  - sites/example.sites.php (https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.4/sites/example.sites.php): Downloading (failed)
  - update.php (https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.4/update.php): Downloading (failed)
  - sites/default/default.services.pantheon.preproduction.yml (https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.4/sites/default/default.services.pantheon.preproduction.yml): Downloading (failed)
  - sites/default/settings.pantheon.php (https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.4/sites/default/settings.pantheon.php): Downloading (failed)

All failing with a 404.

Changing `https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/{version}/{path}` in composer.json to`https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.3/{path}` is a workaround.

Similar past issue: https://github.com/pantheon-systems/drops-8/issues/230

**Comment by greg-1-anderson** [comment]
This will be available soon. In the meantime, drops-8-scaffolding is deprecated. You can avoid this delay by removing it. See HEAD of master for example-drops-8-composer for a guide.

drops-8-scaffolding is not needed by drops-8 users, so closing.

**Comment by greg-1-anderson** [comment]
Also, there is no 8.8.4 release yet. You'll need to wait for Drupal.org to release first.
