### ISSUE TITLE
Cannot import Configuration manager settings

### ISSUE THREAD

**Issue by johncook** [pantheon-systems/drops-8#32]
I am trying to import a Configuration Manager tar-ball, but I get this message:
> Could not extract the contents of the tar file. The error message is Error while opening {./sites/default/config/block.block.classy_admin.yml} in write binary mode

I have tried both a config tar-ball from your server and one from a local Drupal instance clone and neither work. Also, I’ve successfully imported the config from pantheon server into local.

To reproduce:
1. Enable Configuration Manager
2. Go to /admin/config/development/configuration/full/export
3. “Export” config.tar.gz
4. Go to /admin/config/development/configuration/full/import
5. “Choose File” and select the config.tar.gz that was downloaded
6. Click “Upload”
7. Get Error message

**Comment by populist** [comment]
I can confirm this is an issue and will require more research. As a workaround, you can use SFTP or Git to move these files to /sites/default/config and use the synchronize command in the Configuration Manager.

**Comment by populist** [comment]
This should be fixed with the latest rollout of Drupal 8 Beta 10. To see this work, export this tarball from a development instance and then import it into an existing test or live instance.

**Comment by iamjon** [comment]
I just tried to import a dev to test config import on beta 11 and received the same message.

**Comment by dsteplight** [comment]
I just received the same error too. I imagine if I chmod the folder to 777 or something that would resolve the issue after pushing it upstream, but I shouldn't have to do all of that.

**Comment by awolfey** [comment]
Me too on a a fresh install.

**Comment by danielwashbrook** [comment]
Same issue, resolved by chmod 777 the config directory on pantheon via SFTP.

**Comment by stevector** [comment]
`sites/default/config` is kept under version control. For moving configuration exported on a Dev environment up to Test or Live, I recommend doing the following:

1. Make sure the Dev environment is in SFTP mode so that `sites/default/config` is writeable.
2. Use Drush to export configuration (`terminus --env=dev drush "config-export -y"`)
3. Commit the changed yml files with git
4. Deploy to test
5. Import config to test (`terminus --env=test drush "config-import -y"`)
