### ISSUE TITLE
Composer 2 support for 8.9.x

### ISSUE THREAD

**Issue by rajeev-axl** [pantheon-systems/drops-8#350]
Please make 8.9.x composer 2 compatible.

**Comment by greg-1-anderson** [comment]
@rajeev-axl a few points:

1. This repository is just a clone of the Drupal project on drupal.org, with minor additions for the Pantheon platform. We do not / can not add additional features or version compatibility other than what already exists in Drupal itself.
2. Drupal 8.9.x is already Composer 2 compatible.
3. This is not the repository that you would use to make a Composer site on Pantheon.

The repository that you are looking for is [pantheon-upstreams/drupal-project](https://github.com/pantheon-upstreams/drupal-project). See the [Drupal 9](https://pantheon.io/docs/drupal-9) documentation. Integrated Composer support is still in early access on Pantheon; if you want a Composer-managed Drupal 8 site, the best thing to do is create a new Drupal 9 site and then use `composer require` to downgrade it to Drupal 8.9.
