### ISSUE TITLE
Core modules did not update when using Xtheirs

### ISSUE THREAD

**Issue by shermandy** [pantheon-systems/drops-8#365]
Because my site was significantly out of date, Pantheon support recommended that I use the [Xtheirs](https://pantheon.io/docs/core-updates#apply-upstream-updates-manually-from-the-command-line-to-resolve-merge-conflicts) flag to update core. This worked very well but not that I am trying to update modules, I am running into problems. Specifically, I need to apply a security fix for the [ctools](https://www.drupal.org/project/ctools/releases/8.x-3.6) module. It requires 8.8 or above (I'm on 8.9.15) but it appears that my core views module did not update properly. I get an error that traces back to the [code in this file](https://github.com/pantheon-systems/drops-8/blob/default/core/modules/views/src/Plugin/views/display/Block.php). When I checked my core modules folder, I can see that the file wasn't updated. In my admin site, the plugin and Drupal core both report as being up-to-date (8.9.15). Is there anyway I can rectify this?

I will happily give more details. I am new to this and don't know what you might need from me to solve the issue.

**Comment by greg-1-anderson** [comment]
@shermandy Could you please [open a support request](https://pantheon.io/docs/support) for this request? That's the best way to address site-specific issues.

**Comment by shermandy** [comment]
I did and they told me to post it here!

**Comment by panth-jrefuerzo** [comment]
Hello, @greg-1-anderson and @shermandy   Thank you, we'll ticket it so we can investigate further.

**Comment by greg-1-anderson** [comment]
@panth-jrefuerzo If a customer has a support request that is out of scope & cannot be accommodated, please send them to the [Pantheon Community Slack](https://pantheon.io/docs/pantheon-community).

Posting issues in this repository should only be for conditions that affect all sites AND is specific to Pantheon's project template (e.g. is not a general Drupal issue). This only happens for a very narrow cross-section of possible incidents.

**Comment by panth-jrefuerzo** [comment]
I completely agree with you on that @greg-1-anderson  Thanks again!
