### ISSUE TITLE
Undefined $drupal_hash_salt When PRESSFLOW_SETTINGS is Present

### ISSUE THREAD

**Issue by populist** [pantheon-systems/drops-8#37]
In cases where the PRESSFLOW_SETTINGS value is present (i.e. Kalabox) and the $drupal_hash_salt value isn't present, there is an error:

Notice: Undefined variable: drupal_hash_salt in /code/sites/default/settings.php 

Proposed resolution would be to more firmly wrap the setting of the hash salt value to also require that is actually running on Pantheon which sets that value.

**Comment by pirog** [comment]
Ok. So eventually i think we want to somehow inject this directly.. for now using the D8 salt fallback on non pantheony pressflow things a la

```
/**
 * Handle Hash Salt Value from Drupal
 *
 * Issue: https://github.com/pantheon-systems/drops-8/issues/10
 *
 */
if (isset($_SERVER['PRESSFLOW_SETTINGS'])) {
  if (defined('PANTHEON_ENVIRONMENT')) {
    $settings['hash_salt'] = $drupal_hash_salt;
  }
  else {
    $settings['hash_salt'] = hash('sha256', serialize($databases));
  }
}
```

Going to see what it would take on the KB2 end to handle this in the environment instead. If it's not currently worth it will submit the above as a PR for now.

**Comment by populist** [comment]
I am going to close this as a duplidate of #55 which is switching to checking if the site is ON pantheon instead of if PRESSFLOW_SETTINGS exists.
