### ISSUE TITLE
Have Pantheon Allow a *.test File Pattern for D8

### ISSUE THREAD

**Issue by GuyPaddock** [pantheon-systems/drops-8#40]
It looks like the menu paths for things like a node form mode called "test" is formatted like this:
`admin/structure/display-modes/form/manage/node.test`

This triggers a 403 error because I'm guessing that the *.test file pattern is forbidden by nginx extension mappings.

**Comment by greg-1-anderson** [comment]
Confirmed by creating a basic page called "example.test"; this also resulted in a 403.

Other patterns do not result in a 403.

**Comment by greg-1-anderson** [comment]
This has been fixed on the platform.  Note, however, that the Pantheon platform behaves a little differently than a Drupal site using the provided .htaccess site--as would any platform using nginx to serve Drupal.

In the .htaccess, Drupal uses `FileMatch` to exclude serving certain kind of files. Nginx does not have this directive, so `location` is used instead.  The difference here is that `FileMatch` only excludes specific files that exist on disk, whereas Nginx's `location` rejects any *url* that matches.

For Drupal 7, we have the following paths rejected:
```
         location ~ \.(engine|inc|info|install|make|module|profile|test|po|sh|.*sql|theme|tpl(\.php)?|xtmpl)$|^(\..*|Entries.*|Repository|Root|Tag|Template)$ {
             return 403;
         }
```
For Drupal 8, the list is different:
```
        location ~ \.(engine|inc|install|make|module|profile|po|sh|.*sql|theme|twig|tpl(\.php)?|xtmpl|yml)$|^(\..*|Entries.*|Repository|Root|Tag|Template)$ {
             return 403;
         }
```
The end result is that if you create a page and give it the path "test.install", a 403 error will be returned when that path is visited in the web browser.  Similarly, if you try to visit "node.test" on Drupal 7, you will still get a 403, but it will work on Drupal 8.
