### ISSUE TITLE
No way to debug PHP syntax errors

### ISSUE THREAD

**Issue by GuyPaddock** [pantheon-systems/drops-8#42]
It seems like PHP syntax / fatal PHP errors don't show up in any Apache, Nginx, or FPM, logs nor watchdog logs.

I'm trying the Drupal 8 drop on Pantheon, and installed the Prepopulate module (9b5b27b). That module currently has a bug that causes forms that have pre-populated forms to blow up on submit (specifically, node edit forms). The error that PHP actually throws is "Fatal error: [] operator not supported for strings" (https://www.drupal.org/node/2499991), but the only way to find this out was to copy the site locally and use Acquia Dev Desktop.

Nothing in the Pantheon platform was able to provide the error message -- we were just getting a WSOD. We tried turning up the error level, using the Devel module with error handling, etc. This was in the "Dev" environment on Pantheon, too.

I even turned on New Relic support but the errors did not get reported back to New Relic.

Surely there must be a way to get the platform to log these errors somewhere or show them on the page, no?

On Dev Desktop the error showed up on-page immediately, so is it possible that Pantheon has show errors set to FALSE on the server?

**Comment by davidstrauss** [comment]
Please file a support ticket; this is not an issue with the DROPS-8 repository.
