### ISSUE TITLE
Drops-8 is deprecated.  We should update the README.md

### ISSUE THREAD

**Issue by philoSurfer** [pantheon-systems/drops-8#424]
We need a reference back to the 'drupal-composer-managed' in this README.md

https://github.com/pantheon-systems/drupal-composer-managed
@greg-1-anderson ?

**Comment by namespacebrian** [comment]
Note that any changes to the primary branch in this repo become dashboard updates on customer sites using this upstream.  If we make a change to the README.. customers will get a dashboard update... for a README change.

**Comment by greg-1-anderson** [comment]
Also, the README in this repo is expected to match the README from the Drupal upstream.

I modified the GitHub "about" text to point to Drupal Composer Managed instead.

**Comment by philoSurfer** [comment]
> Note that any changes to the primary branch in this repo become dashboard updates on customer sites using this upstream. If we make a change to the README.. customers will get a dashboard update... for a README change.

I think this is a good thing.  We should be pushing our customers to get off this version of Drupal sooner than later.

**Comment by greg-1-anderson** [comment]
We recently discussed the deprecation message, and it was pointed out that we could make a `deprecated` branch in GitHub, and switch the default GitHub branch to that. Then, we could make the README say whatever we want without affecting sites on Pantheon. You'll probably see that change happen in the near future.

I don't think that we need to push notifications about deprecations to customer commit history. Perhaps we could / should have an algorithmic deprecation warning banner on the dashboard for use of any deprecated upstream.

Use of drops-8 will be eliminated as customers upgrade their sites. We recommend switching to drupal-composer-managed as the first step in preparing for a Drupal 9 upgrade. It's possible, although not supported or recommended for folks to stay on drops-8 and still upgrade to Drupal 9, but the site simply won't run on Drupal 10 with drops-8.
