### ISSUE TITLE
Add Git Ignore to DROPS-8

### ISSUE THREAD

**Issue by populist** [pantheon-systems/drops-8#43]
We have a nice .gitignore for DROPS-7 (https://github.com/pantheon-systems/drops-7/blob/master/.gitignore) which can be included in DROPS-8 with whatever updates. 

This hopefully will fix an issue where a symlink for sites/default/files is created which prevents code from being deployed to other environments.

**Comment by populist** [comment]
cc: @nstielau

**Comment by greg-1-anderson** [comment]
I can work this up tomorrow.  I'm just going to look at the .gitignore from drops-7 and combine it with the example .gitignore file in Drupal 8.  I'm going to combine this with #44.

**Comment by nstielau** [comment]
Sounds great Greg!

On Mon, Jun 29, 2015 at 5:13 PM, Greg Anderson <notifications@github.com>
wrote:

> I can work this up tomorrow. I'm just going to look at the .gitignore from
> drops-7 and combine it with the example .gitignore file in Drupal 8. I'm
> going to combine this with #44
> <https://github.com/pantheon-systems/drops-8/pull/44>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pantheon-systems/drops-8/issues/43#issuecomment-116884810>
> .
>



-- 
Nick Stielau | p 415-515-2120
Director of Engineering | Pantheon

**Comment by greg-1-anderson** [comment]
Used a slightly different approach for creating the .gitignore, but I think the one that I put in (very similar to the one in drops-7) will work well.

This is fixed with #44.  Please re-open, or open a new issue if any adjustments are needed.
