### ISSUE TITLE
Initatilizing or Cloning Enviroments Causes Theme Error Due to Hardcoded Path

### ISSUE THREAD

**Issue by populist** [pantheon-systems/drops-8#48]
There is currently a problem between you clone the database between environments where a /srv/binding path is hardcoded into bootstrap_config and key_value which creates an error until the cache is clear (which doesnt seem to happen automagically).

**Comment by populist** [comment]
This operation happens when you initialize new environments or clone environments. A direct cache clear fixes this so its possible that initialize doesnt clear cache and cloning with the "clear cache" option doesnt actually work

**Comment by joshkoenig** [comment]
This could be much more major. If absolute file paths are stored in the DB as part of a code cache, this means multi-container deploys will be broken. 

- Container A will build the cache and store it in the DB
- Container B will read the cache, and the path will be wrong.

This will also cause things to break if we migrate containers on the backend. 

If that's the case, clearing the cache is not a fix and we'll need to get serious about fixing this.

**Comment by greg-1-anderson** [comment]
This is FIXED in the current HEAD of the 8.0.x branch.  I'll leave this open until we deploy beta15 on the platform; it is scheduled to be out on Friday.

First broken: [91c38c8f](http://cgit.drupalcode.org/drupal/commit/?id=91c38c8f)
Fixed: [ec41d082](http://cgit.drupalcode.org/drupal/commit/?id=ec41d082)

**Comment by greg-1-anderson** [comment]
Fixed in beta15 deploy.
