### ISSUE TITLE
Clean up DROPS-8 Settings.php FIle

### ISSUE THREAD

**Issue by populist** [pantheon-systems/drops-8#55]
Before RC we need to make a few cleanups to settings.php:

-- Use $_ENV['PANTHEON_ENVIRONMENT'] as a check for Pantheon
-- Make sure to use proper $drupal_hash_salt value from $_ENV['drupal_hash_salt']
-- Review development.services.yml handling in settings.php
-- Move logic to pantheon.settings.php and include it from settings.php

**Comment by greg-1-anderson** [comment]
All of these fixed in d8b14.
