### ISSUE TITLE
We need to include services.yml from settings.php

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/drops-8#59]
default.settings.php contains this example:
```
/**
 * Load services definition file.
 */
$settings['container_yamls'][] = __DIR__ . '/services.yml';
```
We need to add this to settings.php or settings.pantheon.php; the question is, which one?

Most sites will probably keep this in the default location.  It seems unlikely that Pantheon will ever want to change this value for a customer (further down the road), so I'd guess that it would be more convenient to put it in settings.php.

The distinction is minor, though.

**Comment by gf-pantheon** [comment]
+1 to putting it in settings.php

**Comment by greg-1-anderson** [comment]
The fix for this issue is included in the commits from the new reduced repository.  See #50.
