### ISSUE TITLE
Document or otherwise fix the "Reinstall" instructions.

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/drops-8#74]
If you manually go to `core/install.php` on an installed Drupal 8 site, you will see the following warning message:
```
Drupal already installed
To start over, you must empty your existing database and 
copy default.settings.php over settings.php.
```
It is easy to empty your database with `terminus site wipe --site=xyzzy --env=dev`, and in fact this is all that is necessary to re-install on Pantheon.

**Unfortunately**, if you copy your default.settings.php over your settings.php as the re-install instructions suggest, then you will delete the necessary include of settings.pantheon.php, which will break your Drupal 8 site.

We do not need to deal with this if we successfully replace settings.pantheon.php with injected variables per pantheon-systems/drops-8#56.

**Comment by ttrowell** [comment]
For reference, there was an issue logged on d.o. today:
https://www.drupal.org/node/2591139
Not sure if a change there would affect our solution here.

**Comment by greg-1-anderson** [comment]
That issue will probably be rejected; see above for the standard instructions that Drupal core expects users to go through when re-installing a site.

We are definitely going to continue to need a settings.php file, though; folks need to be educated that it is destructive to erase settings.php when re-installing on Pantheon.

**Comment by joshkoenig** [comment]
We should make sure our tweak is in `default.settings.php` to fix this.

**Comment by greg-1-anderson** [comment]
I didn't want to touch default.settings.php, because I am stubbornly trying not to modify any core files.  However, that course does seem like the best insurance policy. Even if we fixed the instructions, folks who are used to "the Drupal 8 way" could do it by rote without reading.

**Comment by greg-1-anderson** [comment]
The default instructions should be good enough for now, since we have updated settings.php.
