### ISSUE TITLE
Install the Twig C extension

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/drops-8#85]
The Twig C extension ~~greatly~~ decreases ~~increases~~ the render time on Drupal 8 sites.  It cannot  be used unless it is installed on the platform.

See the [installation instructions](http://twig.sensiolabs.org/doc/installation.html#installing-the-c-extension).

**Comment by weitzman** [comment]
FYI, we (acquia) could not find proof that this speeds up anything on modern PHP. We did run own benchmarks though. I wish Drupal did not recommend this so prominently.

**Comment by greg-1-anderson** [comment]
Thanks for the heads up on this. I think that we should definitely benchmark this against PHP 7, and see how much it really helps.

I suspect that the biggest driving force in favor of providing this is going to be quieting the notice you get on the Status Report page if it is not installed.

**Comment by heddn** [comment]
This should be closed as won't fix. The warning for the C extension was removed in 8.1.x.

https://www.drupal.org/node/2568247

**Comment by greg-1-anderson** [comment]
Closing as suggested; I think that's best for now. We can re-open if it looks like this might be worth pursuing in the future.
