### ISSUE TITLE
PHP error "Call to undefined function module_enable()"

### ISSUE THREAD

**Issue by tormi** [pantheon-systems/drops-8#89]
Fresh install gives PHP error ``Call to undefined function module_enable()`` at ``/opt/pantheon/drush-8/vendor/drush/drush/commands/pantheon.drush.inc:161``after commiting settings.php change (``+$settings['install_profile'] = 'standard';``) in SFTP mode.
Site: ``3e00ec8d-59b2-4f75-a9a9-ee29c8152450``

**Comment by greg-1-anderson** [comment]
Duplicate of #19
