### ISSUE TITLE
"Drush 7.0.0 does not support Drupal 8."

### ISSUE THREAD

**Issue by jfrederick** [pantheon-systems/drops-8#95]
For months I have been using Terminus to control a Drupal 8 site. But today when I try to use Terminus or my local drush 8 installation with a remote drush alias, all Drush commands receive this same error: “Drush 7.0.0 does not support Drupal 8.”

Example commands:

terminus drush —site=mysitename —env=dev status

drush8 @pantheon.mysitename.dev status

**Comment by dalin-** [comment]
Same here.  Though when I run without Terminus I get an additional warning message:

```sh
$ drush8 @my-site.dev st
PTY allocation request failed on channel 0
Drush 7.0.0 does not support Drupal 8.                                   [error]
```

**Comment by greg-1-anderson** [comment]
This is a bug on the Pantheon platform that should only affect existing Drupal 8 sites. Create a new Drupal 8.0.0-rc1 site, and you will not have this problem.

For a workaround, [create a local policy](https://pantheon.io/blog/fix-drush-site-aliases-policy-file) file pointing to drush8. This will allow you to use Drush with an alias to operate on your old site. There is no workaround for Terminus.

Note that sites created in the Drupal 8 Testing org will eventually be swept into the site freezer; you cannot go live with sites in the Testing org.

**Comment by jfrederick** [comment]
Thanks for the info, Greg.

"Note that sites created in the Drupal 8 Testing org will eventually be swept into the site freezer; you cannot go live with sites in the Testing org."

Does this mean that rather than upgrading our current site from beta15 to rc1 as we expected to, we will actually have to create a new rc1 environment on Pantheon, and then import our site into that environment for it to be launchable? In order to avoid being trapped in the "Testing org"?

**Comment by bmackinney** [comment]
That's correct. You'll be able/prompted to do that very soon.

**Comment by greg-1-anderson** [comment]
We're not going to do anything further here; folks must work around the problem as described above, or make a new site and migrate. Closing.
