### ISSUE TITLE
Install using MINIMAL profile throws errors on trying to write / create settings.php file.

### ISSUE THREAD

**Issue by alphex** [pantheon-systems/drops-8#98]
see screen shot here : http://z.alphex.io/2015-10-14_15-03-07.jpg

Normal steps.  
Pick pick language.
Pick distribution : I picked Minimal.
*boom* got this error 

Error
Error message
Warning: file_put_contents(sites/default/settings.php): failed to open stream: Permission denied in drupal_rewrite_settings() (line 338 of core/includes/install.inc).
drupal_rewrite_settings(Array)
install_write_profile(Array)
install_run_task(Array, Array)
install_run_tasks(Array)
install_drupal(Object)
The website encountered an unexpected error. Please try again later.
Exception: Failed to modify <em class="placeholder">sites/default/settings.php</em>. Verify the file permissions. in drupal_rewrite_settings() (line 339 of core/includes/install.inc).
drupal_rewrite_settings(Array)
install_write_profile(Array)
install_run_task(Array, Array)
install_run_tasks(Array)
install_drupal(Object)

**Comment by greg-1-anderson** [comment]
If you are re-installing a site that you installed once before, you must first WIPE the site from your Dashboard Workflows or via Terminus before you can install again.

Once you fix that problem, you will run into #96. I suggest that you install the Standard profile for now.

**Comment by alphex** [comment]
I went to the SETTINGS menu in the site dashboard, and clicked delete, then
typed the site name to confirm the delete, then pressed the delete button.

Is that not enough?

**Comment by greg-1-anderson** [comment]
No, the operation you describe above will break a Pantheon Drupal site; it is necessary to have a settings.php file, and it must include settings.pantheon.php.  You must restore your settings.php file and wipe the site to continue (or start over with a new site).

**Comment by alphex** [comment]
Alright, sorry, to be clear...  perfectly clear.

1. I click on settings, and click delete. 
![2015-10-14 16-31-16](https://cloud.githubusercontent.com/assets/597641/10496949/35b1fc90-7291-11e5-92e4-e5b1e999f1ef.jpg)

2. I click Delete, and type in the site name and click the big red button.
![2015-10-14 16-33-05](https://cloud.githubusercontent.com/assets/597641/10496961/4e69b282-7291-11e5-9efa-d044b9bd51ac.jpg)

This returns me to my master list of sites.

Shouldn't this completely wipe the site, and all references to it? and allow me to try to recreate it with the same name, safely?

**Comment by bmackinney** [comment]
@alphex yes, you should be able to recreate the site at https://dashboard.pantheon.io/sites/create, after deleting it.

**Comment by greg-1-anderson** [comment]
Sorry, @alphex, I misread your initial question!

The procedure you outline above will completely DELETE the site in question. You could then start over and create a new site.  If you want to re-install a site, then you can use the WIPE function from the WORKFLOW section on your dashboard.

![screen shot 2015-10-14 at 1 43 47 pm](https://cloud.githubusercontent.com/assets/612191/10497228/a984c980-7279-11e5-8cb0-b3b67c54645d.png)

**Comment by alphex** [comment]
Ok,
Then I'm deleting the site correctly :)
Thanks for the follow up @greg-1-anderson 

#96 is the issue then.  Until installing in git mode is fixed.

I'm going to close this.
Thank you for your responses!
